### ISSUE TITLE
Auto completion for imports does not work

### ISSUE THREAD

**Issue by TimKack** [tunnelvisionlabs/goworks#4]
Admittedly I have not looked deep into this yet, but auto completion of symbols in imports does not work.
Consider:

``` go
    package main
    import "fmt"

    func main() {
    fmt.Println("Hello, 世界")
        fmt. // <---- at the dot I do not get any suggestions from the fmt package
   }
```

The Netbeans ide log reports:

```
WARNING [org.tvl.goworks.editor.go.completion.GoCompletionQuery]: Unable to resolve unqualified link from qualifier: [receiverType methodExpr operand expression simpleStmt statement block body functionDecl topLevelDecl sourceFileBody]
```

**Comment by sharwell** [comment]
Based on the date of this issue and the release date of Go 1.4, I believe this is caused by #9.

**Comment by sharwell** [comment]
:memo: Sorry for the delayed response. The project has been mostly dormant considering the broader Go community's reluctance to try out a Java-based IDE (at least this was my experience during the time I was more active on it).
